# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets
from registration_window import registration_window1
con = mc.connect(host='Localhost',user='root',passwd='cadburychocolate123',db='2playergames')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../pictures/login bg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 40, 371, 251))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(870, 270, 311, 31))
        self.lineEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(770, 270, 121, 51))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(870, 350, 311, 31))
        self.lineEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(775, 340, 121, 51))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(810, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1020, 500, 151, 28))
        self.pushButton_2.setObjectName("pushButton2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # TEXT FOR INVALID USERNAME
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText('User does not exist')
        self.label_5.move(1200, 275)
        self.label_5.setStyleSheet("color: red")
        self.label_5.setHidden(True)

        # TEXT FOR INVALID PASSWORD
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText('Invalid password')
        self.label_6.move(1200, 360)
        self.label_6.setStyleSheet("color: red")
        self.label_6.setHidden(True)

        # CONNECTING USER_AND_PASS METHOD TO LOGIN BUTTON
        self.pushButton.clicked.connect(self.user_and_pass)

        self.pushButton_2.clicked.connect(self.window2)

    # METHOD TO VERIFY USERNAME AND PASSWORD
    def user_and_pass(self):
        un = self.lineEdit.text()
        pw = self.lineEdit_2.text()
        cr = con.cursor()
        a = cr.execute('select * from bank')
        a = cr.fetchall()
        count=0
        for x in a:
            if un == x[0]:
                count+=1
        if count == 1:
            cr = con.cursor()
            a = cr.execute('select * from bank')
            a = cr.fetchall()
            for x in a:
                if un == x[0] and x[1] == pw:
                    count += 1
            if count == 2:
                pass
            else:
                self.label_5.setHidden(True)
                self.label_6.setHidden(False)
        else:
            self.label_5.setHidden(False)
            self.label_6.setHidden(True)


    def window2(self):
        self.w = registration_window1
        self.w.show()
        self.hide()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#00ff00;\">WELCOME BACK</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Username</span></p><p><span style=\" font-size:12pt; color:#ffffff;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_2.setText(_translate("MainWindow", "Don\'t Have An Account?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
